<?xml version="1.0" encoding="UTF-8"?>
<pmd xmlns="http://pmd.sourceforge.net/report/2.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pmd.sourceforge.net/report/2.0.0 http://pmd.sourceforge.net/report_2_0_0.xsd" version="6.44.0" timestamp="2023-10-12T15:52:29.129">
<file name="/mnt/c/Users/Valentino/Documents/Universita/Tesi/Tesi/Pacchetto_di_replicabilita/Correttiva/src/CWE-20/bad$ad31479c1c543ac7d26b8c882aa14f6c00c1fd0$114$DefaultReportJobDelegate.java">
<violation beginline="168" endline="168" begincolumn="21" endcolumn="106" rule="GuardLogStatement" ruleset="Best Practices" package="org.apache.syncope.core.provisioning.java.job.report" class="DefaultReportJobDelegate" method="execute" externalInfoUrl="https://pmd.github.io/pmd-6.44.0/pmd_rules_java_bestpractices.html#guardlogstatement" priority="2">
Logger calls should be surrounded by log level guards.
</violation>
<violation beginline="186" endline="197" begincolumn="23" endcolumn="21" rule="AvoidCatchingThrowable" ruleset="Error Prone" package="org.apache.syncope.core.provisioning.java.job.report" class="DefaultReportJobDelegate" method="execute" externalInfoUrl="https://pmd.github.io/pmd-6.44.0/pmd_rules_java_errorprone.html#avoidcatchingthrowable" priority="3">
A catch statement should never catch throwable since it includes errors.
</violation>
<violation beginline="191" endline="191" begincolumn="47" endcolumn="47" rule="AvoidInstanceofChecksInCatchClause" ruleset="Error Prone" package="org.apache.syncope.core.provisioning.java.job.report" class="DefaultReportJobDelegate" method="execute" externalInfoUrl="https://pmd.github.io/pmd-6.44.0/pmd_rules_java_errorprone.html#avoidinstanceofchecksincatchclause" priority="3">
An instanceof check is being performed on the caught exception.  Create a separate catch clause for this exception type.
</violation>
</file>
</pmd>
